# Makefile include for specifying the target
# This file is automatically updated by run_basic_tests.sh

TARGET_DIR := basic_examples
TARGET_SRC := 6_9_conditional.S
ASFLAGS_TARGET := -march=rv64gc -g
